### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by YYHYlh** [zhanghuanhao/WireWhale#1]
执行 python main.py的时候报了这个错
`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from main_ui import start
  File "/Users/lllh/Desktop/botnet/WireWhale-master/main_ui.py", line 6, in <module>
    from capture_core import *
  File "/Users/lllh/Desktop/botnet/WireWhale-master/capture_core.py", line 18, in <module>
    platform, netcards = get_nic_list()
TypeError: cannot unpack non-iterable NoneType object`

**Comment by YYHYlh** [comment]
找到问题的原因了，在mac平台下platfform库的system函数返回的是Darwin.
